config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'competition' => 'competitions#index'
  get 'competitions/team/:id' => 'competitions#team'
  get 'competitions/shows' => 'competitions#shows'
  get 'competitions/login_in' => 'competitions#login_in'
  resources :competitions, only: [:index, :show] do
    collection do
      post :valid_create_team
      post :add_user_apply_info
      get :apply_in
      get :event_teams
      post :reduce_team_amount
      post :delete_team
      post :leader_delete_player
      post :valid_team_code
      post :send_email_code
      post :reset_team_code_by_mobile
      post :reset_team_code_by_email
    end
  end
  resources :creative_activities
  resources :news

  devise_for :users, path: 'account', controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  captcha_route

  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  mount API_v1::API => '/'

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/mobile' => 'user#mobile', as: 'user_mobile', via: [:get, :post]
  match 'user/add_mobile' => 'user#add_mobile', as: 'user_add_mobile', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get, :post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get, :post]
  match 'user/creative_activity' => 'user#creative_activity', as: 'user_creative_activity', via: [:get, :post]
  get 'user/activity_show' => 'user#activity_show'
  get 'user/comp_show' => 'user#comp_show'
  post 'user/update_team_cover' => 'user#update_team_cover', as: 'user_update_team_cover'
  get 'discourse/sso' => 'discourse_sso#sso'
  namespace :user do |u|

    resources :likes, only: [:index, :create, :destroy]

  end
  get 'test' => 'test#index'

  get '/admin/' => 'admin#index'

  namespace :admin do |admin|

    resources :accounts, only: [:new, :index, :create, :destroy] do
      collection do
        get :change_password
        post :change_password_post
      end
    end

    resources :admins
    resources :competitions do
      collection do
        get :get_events
      end
    end
    resources :events do
      collection do
        get :teams
        get :scores
        get :add_score
        post :add_score
        get :edit_score
        post :edit_score
        post :create_team
        post :add_team_player
        post :delete_team_player
        post :delete_team
      end
    end
    resources :users
    resources :organizers
    resources :teams
    resources :creative_activities do
      collection do
        post :add_expert_score
        post :edit_expert_score
        post :audit
      end
    end
    resources :scores do
      collection do
        post :get_teams
      end
    end
    resources :news
    resources :news_types
    resources :schedules
    resources :referees
    resources :roles
    resources :districts
    resources :vouchers

  end

  namespace :kindeditor do
    post '/upload' => 'assets#create'
    get '/filemanager' => 'assets#list'
  end

  if Rails.env.development?
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :competition
  has_many :teams
  has_many :scores
  has_many :team_user_ships, through: :team
  has_many :creative_activities
  has_many :news
  mount_uploader :cover, EventUploader

  validates :name, presence: true
  validates :competition_id, presence: true
  validates :status, presence: true
  before_save :update_level

  def update_level
    if self.parent_id.present?
      self.level = 2
    end
  end
  # validates :team_min_num, presence: true
  # validates :team_max_num, presence: true
  # validates :apply_start_time, presence: true
  # validates :apply_end_time, presence: true
  # validates :start_time, presence: true
  # validates :end_time, presence: true
  # validate :validate_datetime

  # def validate_datetime
  #   if apply_start_time.present? and apply_end_time.present? and start_time.present? and end_time.present?
  #     if apply_end_time < apply_start_time
  #       errors[:apply_start_time] << '报名结束时间不能早于报名开始时间'
  #     end
  #     if start_time < apply_end_time
  #       errors[:start_time] << '比赛开始时间不能早于报名结束时间'
  #     end
  #     if start_time > end_time
  #       errors[:end_time] << '比赛结束时间不能早于比赛开始时间'
  #     end
  #   else
  #     errors[:end_time] << '比赛报名起始时间和比赛起始时间为必填项'
  #   end
  # end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /admin/events
  # GET /admin/events.json
  def index
    if params[:field].present? && params[:keyword].present?
      @events = Event.all.where(["#{params[:field]} like ?", "%#{params[:keyword]}%"]).per_page_kaminari(params[:page]).per(params[:per])
    else
      @events = Event.all.per_page_kaminari(params[:page]).per(params[:per])
    end
  end

  # GET /admin/events/1
  # GET /admin/events/1.json
  def show
    @users = User.where(validate_status: 1)
  end


  # GET /admin/events/new
  def new
    @event = Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events
  # POST /admin/events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: '比赛项目创建成功' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def scores
    @event = Event.find(params[:id])
    @scores = Score.where(event_id: params[:id]).page(params[:page]).per(params[:per])
  end

  ## 添加比赛成绩
  def add_score
    @score = Score.new
    # @competition = Competition.find(params[:id])
    if params[:sid].present?
      @plus_score = Score.find(params[:sid])
      @score.event_id = @plus_score.event_id
      @score.comp_name = @plus_score.comp_name
      @score.kind = @plus_score.kind
      @score.th = @plus_score.th
      @score.team1_id = @plus_score.team1_id
      @score.team2_id = @plus_score.team2_id
      @score.score1 = @plus_score.score1
      @score.score2 = @plus_score.score2
      @score.referee_id = @plus_score.referee_id
    end


    if request.method == 'POST'

      @score = Score.new(score_params)
      respond_to do |format|
        if @score.save
          format.html { redirect_to "#{scores_admin_events_path}?id=#{@score.event_id}", notice: '成绩添加成功.' }
          format.json { render action: 'add_score', status: :created, location: @score }
        else
          format.html { render action: 'add_score' }
          format.json { render json: @score.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # 编辑比赛成绩
  def edit_score
    @score = Score.find(params[:id])
    if request.method == 'POST'
      respond_to do |format|
        if @score.update(score_params)
          format.html { redirect_to "#{scores_admin_events_path}?id=#{@score.event_id}", notice: '成绩更新成功' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit_score' }
          format.json { render json: @score.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  def teams
    @event = Event.find(params[:id])
    @teams = Team.where(event_id: params[:id]).page(params[:page]).per(params[:per])
    @users = User.includes(:user_profile).where(validate_status: 0).where.not(id: TeamUserShip.where(event_id: params[:id]).pluck(:user_id)).select(:id, :nickname)
    @against = Team.where(event_id: params[:id]).pluck(:id).shuffle.each_slice(2).to_a
  end

  def create_team
    user_id = params[:user_id]
    t = TeamUserShip.where(user_id: user_id, event_id: params[:event_id]).take
    team_name = Team.where(event_id: params[:event_id], name: params[:team_name]).take
    if t.present?
      result = [false, '该队长已经报名此比赛,不能参与两个队伍!']
    elsif team_name.present?
      result = [false, '很抱歉，该比赛中队伍['+team_name.name+']已存在，请更改队伍名称!']
    else
      team = Team.create!(name: params[:team_name], user_id: user_id, event_id: params[:event_id], team_code: params[:team_code], teacher: params[:teacher])
      team_user_ship = TeamUserShip.create!(team_id: team.id, user_id: team.user_id, event_id: params[:event_id])
      if team.save && team_user_ship.save
        result = [true, '队伍['+team.name+']创建成功!']
      else
        team_user_ship.destroy
        result = [false, '队伍创建失败']
      end
    end
    render json: result
  end

  def add_team_player
    user_ids = params[:user_ids]
    team_id = params[:team_id]
    # event_id = params[:event_id]
    if user_ids.length > 4
      result = [false, '一次最多添加四名队员']
    else
      message = ''
      user_ids.each do |ud|
        user = User.find(ud)
        player = TeamUserShip.new(team_id: team_id, user_id: ud)#, event_id: event_id)
        player.save
        if player.save
          message = user.nickname + '添加成功' + message.to_s
        else
          message = user.nickname + '添加失败' + message.to_s
        end
      end
      result = [true, message]
    end
    render json: result
  end


  def delete_team_player
    user_id = params[:user_id]
    team_id = params[:team_id]
    player = TeamUserShip.where(user_id: user_id, team_id: team_id).take
    player.destroy
    if player.destroy
      result = [true, '删除成功']
    else
      result = [false, '删除失败']
    end
    render json: result
  end

  def delete_team
    Team.delete(params[:team_id])
    players = TeamUserShip.where(team_id: params[:team_id])
    players.delete_all
    if players.delete_all
      result = [true, '删除成功']
    else
      result = [false, '删除失败']
    end
    render json: result
  end

  # PATCH/PUT /admin/events/1
  # PATCH/PUT /admin/events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [:admin, @event], notice: '比赛项目更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1
  # DELETE /admin/events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: '比赛项目删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit!
  end

  def score_params
    params.require(:score).permit(:event_id, :comp_name, :kind, :th, :team1_id, :team2_id, :score1, :score2, :referee_id, :operator)
  end
end

app/views/admin/events/add_score.html.erb
<h1 class="page-header">
  新增成绩
  <small class="pull-right">
    <a href="<%= "#{scores_admin_events_path}?id=#{params[:eid]}" %>" class="btn btn-default" title="成绩列表">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>
<style type="text/css">
    .row:after {
        clear: right;
    }
</style>
<div class="panel panel-info">
  <div class="panel-heading"><%= t('activerecord.models.score') %></div>
  <div class="panel-body">
    <%= simple_form_for(@score, url: "#{add_score_admin_events_path}?id=#{params[:id].present? ? params[:id] : @score.event_id}", method: :post) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :comp_name, collection: Schedule.all, prompt: '请选择' %>
          <%= f.input :kind, collection: Score::KIND.map { |key, val| [t('kind.'+key.to_s), val] }, prompt: 1 %>
          <div class="row">
            <div class="col-xs-12">
              <div class="row">
                <div class="col-xs-4"><%= f.input :th, collection: 1..11, prompt: '请选择' %></div>
                <div class="col-xs-4"><%= f.input :team1_id, collection: Team.where(event_id: params[:id].present? ? params[:id] : @score.event_id) %></div>
                <div class="col-xs-4"><%= f.input :team2_id, collection: Team.where(event_id: params[:id].present? ? params[:id] : @score.event_id) %></div>
              </div>
            </div>

          </div>
          <div class="row">
            <div class="col-xs-12">
              <div class="row">
                <div class="col-xs-4"><%= f.input :referee_id %></div>
                <div class="col-xs-4"><%= f.input :score1 %></div>
                <div class="col-xs-4"><%= f.input :score2 %></div>
              </div>
            </div>
          </div>
          <%= f.hidden_field :operator, value: @current_admin.id %>
          <%= f.hidden_field :event_id, value: params[:id].present? ? params[:id] : @score.event_id %>
        </div>
        <div class="clearfix"></div>
        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary add-mark-score' %>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    window.onload = function () {
        var score_kind = $('#score_kind').val();
        if (score_kind == '1') {
            $('.score_team2_id,.score_score2').addClass('hidden');
        } else {
            $('.score_team2_id,.score_score2').removeClass('hidden');
        }
    };
</script>

app/views/admin/events/edit.html.erb
<h1 class="page-header">
  编辑<%= t('activerecord.models.event') %>
  <small class="pull-right">
    <a href="<%= admin_event_path(@event) %>" title="显示该比赛项目" class="btn btn-default">
      <i class="icon-eye-open icon-only"></i></a>
    <a href="<%= admin_events_path %>" title="比赛项目列表" class="btn btn-default">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<%= render 'form' %>

app/views/admin/events/edit_score.html.erb
<h1 class="page-header">
  编辑成绩
  <small class="pull-right">
    <a href="<%= "#{scores_admin_events_path}?id=#{@score.event_id}" %>" class="btn btn-default" title="成绩列表">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<div class="panel panel-info">
  <div class="panel-heading"><%= t('activerecord.models.score') %></div>
  <div class="panel-body">

    <%= simple_form_for(@score, url: "#{edit_score_admin_events_path}?id=#{@score.id}", method: :post) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :comp_name, collection: Schedule.all, prompt: '请选择' %>
          <%= f.input :kind, collection: Score::KIND.map { |key, val| [t('kind.'+key.to_s), val] }, prompt: '请选择' %>
          <div class="row">
            <div class="col-xs-4"><%= f.input :th, collection: [1, 2, 3, 4, 5, 6], prompt: '请选择' %></div>
            <div class="col-xs-4"><%= f.input :team1_id, collection: Team.where(event_id: @score.event_id) %></div>
            <div class="col-xs-4"><%= f.input :team2_id, collection: Team.where(event_id: @score.event_id) %></div>
          </div>
          <div class="row">
            <div class="col-xs-4"><%= f.input :referee_id %></div>
            <div class="col-xs-4"><%= f.input :score1 %></div>
            <div class="col-xs-4"><%= f.input :score2 %></div>
          </div>

          <%= f.hidden_field :operator, value: @current_admin.id %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary add-mark-score' %>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    window.onload = function () {
        var score_kind = $('#score_kind').val();
        if (score_kind == '1') {
            $('.score_team2_id,.score_score2').addClass('hidden');
        } else {
            $('.score_team2_id,.score_score2').removeClass('hidden');
        }
    }
</script>

app/views/admin/events/index.html.erb
<h1 class="page-header">
  <%= t('activerecord.models.event') %>列表
  <small class="pull-right">
    <a href="<%= new_admin_event_path %>" class="btn btn-default" title="添加比赛项目">
      <i class="icon-only icon-plus"></i></a>
    <a href="#" class="btn btn-default btn-search-toggle" title="搜索">
      <i class="icon-search icon-only"></i>
    </a>
  </small>
</h1>
<div class="widget-box form-search-toggle <%= params[:field].present? && params[:keyword].present? ? 'show' : 'hide' %>">
  <div class="widget-header widget-header-small">
    <h5 class="lighter">搜索</h5>
  </div>
  <div class="widget-body">
    <div class="widget-main">
      <form class="form" role="form" method="get">
        <div class="input-group" data-search="field">
          <div class="input-group-btn">
            <button type="button" class="btn btn-white dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
              <span data-search-text class="admin-search-field"><%= t('simple_form.labels.defaults.name') %></span>
              <span class="caret"></span></button>
            <ul class="dropdown-width dropdown-menu">
              <li data-search-option="name"><a><%= t('simple_form.labels.defaults.name') %></a></li>
              <li data-search-option="id"><a>ID</a></li>
            </ul>
          </div>
          <input type="hidden" name="field" value="<%= params[:field].present? ? params[:field] : 'name' %>"/>
          <input placeholder="输入关键字，按回车键提交" value="<%= params[:keyword] %>" name="keyword" type="text" class="form-control" aria-label="...">
        </div>
      </form>
    </div>
  </div>
</div>

<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th><%= t('simple_form.labels.defaults.name') %></th>
    <th><%= t('simple_form.labels.defaults.competition_id') %></th>
    <th>项目状态</th>
    <th>每队人数</th>
    <th>操作</th>
  </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.name %></td>
        <td><%= event.competition.try(:name) %></td>
        <td><%= t('status.status'+event.status.to_s) %></td>
        <td><%= "#{event.team_min_num}-" if event.team_min_num != event.team_max_num %><%= event.team_max_num %></td>
        <td>

          <%= link_to [:admin, event], title: '查看', class: 'btn btn-xs btn-warn' do %>
              <i class="icon-eye-open bigger-120"></i>
          <% end %>
          <%= link_to "#{teams_admin_events_path}?id=#{event.id}", title: '队伍', class: 'btn btn-xs btn-primary' do %>
              <i class="icon-flag-alt bigger-120"></i>
          <% end %>
          <%= link_to "#{scores_admin_events_path}?id=#{event.id}", title: '成绩列表', class: 'btn btn-xs btn-success' do %>
              <i class="icon-book icon-only"></i>
          <% end %>
          <%= link_to edit_admin_event_path(event), title: '编辑', class: 'btn btn-xs btn-info' do %>
              <i class="icon-edit bigger-120"></i>
          <% end %>
          <%= link_to [:admin, event], method: :delete, data: {confirm: '确认删除吗?'}, title: '删除', class: 'btn btn-xs btn-danger' do %>
              <i class="icon-trash bigger-120"></i>
          <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<nav>
  <%= paginate @events %>
</nav>

app/views/admin/events/new.html.erb
<h1 class="page-header">
  新增<%= t('activerecord.models.event') %>
  <small class="pull-right">
    <a href="<%= admin_events_path %>" class="btn btn-default" title="比赛项目列表">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<%= render 'form' %>

app/views/admin/events/scores.html.erb
<h1 class="page-header">
  <%= @event.name %> <%= t('activerecord.models.score') %>列表
  <small class="pull-right">
    <a href="<%= "#{add_score_admin_events_path}?id=#{@event.id}" %>" class="btn btn-default" title="添加成绩">
      <i class="icon-only icon-plus"></i></a>
    <a href="#" class="btn btn-default btn-search-toggle" title="搜索">
      <i class="icon-search icon-only"></i>
    </a>
  </small>
</h1>
<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th><%= t('simple_form.labels.defaults.comp_name') %></th>
    <th><%= t('simple_form.labels.defaults.kind') %></th>
    <th><%= t('simple_form.labels.defaults.team1_id') %></th>
    <th><%= t('simple_form.labels.defaults.th') %></th>
    <th>分数</th>
    <th><%= t('simple_form.labels.defaults.referee_id') %></th>
    <th><%= t('simple_form.labels.defaults.operator') %></th>
    <th>操作</th>
  </tr>
  </thead>

  <tbody>
  <% @scores.each do |score| %>
      <tr>
        <td><%= score.id %></td>
        <td><%= score.schedule.try(:name) %></td>
        <td><%= t('kind.kind'+score.kind.to_s) %></td>
        <td><%= score.team1.name %><%= " - #{score.team2.name}" if score.kind == 2 %></td>
        <td><%= score.th %></td>
        <td><%= score.score1 %><%= " : #{score.score2} " if score.kind == 2 %></td>
        <td><%= score.referee_id %></td>
        <td><%= score.admin.try(:name) %></td>
        <td>
          <%= link_to add_score_admin_events_path + '?sid='+ score.id.to_s+'&eid='+@event.id.to_s, title: '引用添加', class: 'btn btn-xs btn-default' do %>
              <i class="glyphicon glyphicon-plus"></i>
          <% end %>
          <%= link_to "#{edit_score_admin_events_path}?id=#{score.id}", title: '编辑', class: 'btn btn-xs btn-info' do %>
              <i class="icon-edit icon-only"></i>
          <% end %>
          <%= link_to [:admin, score], method: :delete, data: {confirm: '确认删除吗?'}, title: '删除', class: 'btn btn-xs btn-danger' do %>
              <i class="icon-trash icon-only"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>

</table>


<nav>
  <%= paginate @scores %>
</nav>

app/views/admin/events/show.html.erb
<h1 class="page-header">
  显示<%= t('activerecord.models.event') %>
  <small class="pull-right">
    <a href="<%= new_admin_event_path %>" title="添加项目" class="btn btn-default">
      <i class="icon-plus icon-only"></i></a>
    <a href="<%= edit_admin_event_path(@event) %>" title="编辑" class="btn btn-default">
      <i class="icon-edit icon-only"></i></a>
    <a href="<%= admin_events_path %>" title="列表" class="btn btn-default">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>
<div class="panel panel-info">
  <div class="panel-heading">
    <%= t('activerecord.models.event') %>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <h4><%= t('simple_form.labels.defaults.name') %>:</h4>

      <%= @event.name %>
    </li>
    <li class="list-group-item">
      <h4><%= t('simple_form.labels.defaults.competition_id') %>:</h4>

      <%= @event.competition.name %>
    </li>
    <li class="list-group-item">
      <h4>每队人数:</h4>

      <%= @event.team_min_num %><%= " - #{@event.team_max_num}" if @event.team_max_num != @event.team_min_num %>
    </li>
    <li class="list-group-item">
      <h4><%= t('simple_form.labels.defaults.description') %>:</h4>

      <%= @event.description %>
    </li>
    <li class="list-group-item">
      <h4>封面:</h4>
      <% if @event.cover.present? %>
          <%= image_tag(@event.cover_url(:middle)) %>
      <% end %>
    </li>
    <li class="list-group-item">
      <h4>状态:</h4>

      <%= t('status.status'+@event.status.to_s) %>
    </li>
    <li class="list-group-item">
      <h4>比赛开始时间:</h4>

      <%= @event.start_time.try(:strftime, '%Y-%m-%d %H:%M') %>
    </li>
    <li class="list-group-item">
      <h4>比赛结束时间:</h4>

      <%= @event.end_time.try(:strftime, '%Y-%m-%d %H:%M') %>
    </li>
  </ul>
</div>