config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'competition' => 'competitions#index'
  get 'competitions/team/:id' => 'competitions#team'
  get 'competitions/shows' => 'competitions#shows'
  get 'competitions/login_in' => 'competitions#login_in'
  resources :competitions, only: [:index, :show] do
    collection do
      post :valid_create_team
      post :add_user_apply_info
      get :apply_in
      get :event_teams
      post :reduce_team_amount
      post :delete_team
      post :leader_delete_player
      post :valid_team_code
      post :send_email_code
      post :reset_team_code_by_mobile
      post :reset_team_code_by_email
    end
  end
  resources :creative_activities
  resources :news

  devise_for :users, path: 'account', controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  captcha_route

  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  mount API_v1::API => '/'

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/mobile' => 'user#mobile', as: 'user_mobile', via: [:get, :post]
  match 'user/add_mobile' => 'user#add_mobile', as: 'user_add_mobile', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get, :post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get, :post]
  match 'user/creative_activity' => 'user#creative_activity', as: 'user_creative_activity', via: [:get, :post]
  get 'user/activity_show' => 'user#activity_show'
  get 'user/comp_show' => 'user#comp_show'
  post 'user/update_team_cover' => 'user#update_team_cover', as: 'user_update_team_cover'
  get 'discourse/sso' => 'discourse_sso#sso'
  namespace :user do |u|

    resources :likes, only: [:index, :create, :destroy]

  end
  get 'test' => 'test#index'

  get '/admin/' => 'admin#index'

  namespace :admin do |admin|

    resources :accounts, only: [:new, :index, :create, :destroy] do
      collection do
        get :change_password
        post :change_password_post
      end
    end

    resources :admins
    resources :competitions do
      collection do
        get :get_events
      end
    end
    resources :events do
      collection do
        get :teams
        get :scores
        get :add_score
        post :add_score
        get :edit_score
        post :edit_score
        post :create_team
        post :add_team_player
        post :delete_team_player
        post :delete_team
      end
    end
    resources :users
    resources :organizers
    resources :teams
    resources :creative_activities do
      collection do
        post :add_expert_score
        post :edit_expert_score
        post :audit
      end
    end
    resources :scores do
      collection do
        post :get_teams
      end
    end
    resources :news
    resources :news_types
    resources :schedules
    resources :referees
    resources :roles
    resources :districts
    resources :vouchers

  end

  namespace :kindeditor do
    post '/upload' => 'assets#create'
    get '/filemanager' => 'assets#list'
  end

  if Rails.env.development?
  end

end

app/controllers/admin/news_types_controller.rb
class Admin::NewsTypesController < AdminController
  before_action :set_news_type, only: [:show, :edit, :update, :destroy]

  # GET /admin/news_types
  # GET /admin/news_types.json
  def index
    if params[:field].present? && params[:keyword].present?
      @news_types = NewsType.all.where(["#{params[:field]} like ?", "%#{params[:keyword]}%"]).per_page_kaminari(params[:page]).per(params[:per])
    else
      @news_types = NewsType.all.per_page_kaminari(params[:page]).per(params[:per])
    end
  end

  # GET /admin/news_types/1
  # GET /admin/news_types/1.json
  def show
  end

  # GET /admin/news_types/new
  def new
    @news_type = NewsType.new
  end

  # GET /admin/news_types/1/edit
  def edit
  end

  # POST /admin/news_types
  # POST /admin/news_types.json
  def create
    @news_type = NewsType.new(news_type_params)

    respond_to do |format|
      if @news_type.save
        format.html { redirect_to [:admin, @news_type], notice: '新闻类型创建成功!' }
        format.json { render action: 'show', status: :created, location: @news_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @news_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/news_types/1
  # PATCH/PUT /admin/news_types/1.json
  def update
    respond_to do |format|
      if @news_type.update(news_type_params)
        format.html { redirect_to [:admin, @news_type], notice: '新闻类型更新成功!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/news_types/1
  # DELETE /admin/news_types/1.json
  def destroy
    @news_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_news_types_url, notice: '新闻类型删除成功!' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_news_type
    @news_type = NewsType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_type_params
    params.require(:news_type).permit(:name)
  end
end

app/views/admin/news_types/_form.html.erb
<div class="panel panel-info">
  <div class="panel-heading"><%= t('activerecord.models.news_type') %></div>
  <div class="panel-body">
    <%= simple_form_for([:admin, @news_type]) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :name %>
        </div>

        <div class="form-actions">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/admin/news_types/edit.html.erb
<h1 class="page-header">
  编辑<%= t('activerecord.models.news_type') %>
  <small class="pull-right">
    <a href="<%= admin_news_type_path(@news_type) %>" title="显示该新闻类型" class="btn btn-default">
      <i class="icon-eye-open icon-only"></i></a>
    <a href="<%= admin_news_types_path %>" title="新闻类型列表" class="btn btn-default">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<%= render 'form' %>

app/views/admin/news_types/index.html.erb
<h1 class="page-header">
  <%= t('activerecord.models.news_type') %>列表
  <small class="pull-right">
    <a href="<%= new_admin_news_type_path %>" class="btn btn-default" title="添加新闻类型">
      <i class="icon-only icon-plus"></i></a>
    <a href="#" class="btn btn-default btn-search-toggle" title="搜索">
      <i class="icon-search icon-only"></i>
    </a>
  </small>
</h1>
<div class="widget-box form-search-toggle <%= params[:field].present? && params[:keyword].present? ? 'show' : 'hide' %>">
  <div class="widget-header widget-header-small">
    <h5 class="lighter">搜索</h5>
  </div>
  <div class="widget-body">
    <div class="widget-main">
      <form class="form" role="form" method="get">
        <div class="input-group" data-search="field">
          <div class="input-group-btn">
            <button type="button" class="btn btn-white dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
              <span data-search-text class="admin-search-field"><%= t('simple_form.labels.defaults.name') %></span>
              <span class="caret"></span></button>
            <ul class="dropdown-width dropdown-menu">
              <li data-search-option="name"><a><%= t('simple_form.labels.defaults.name') %></a></li>
              <li data-search-option="id"><a>ID</a></li>
            </ul>
          </div>
          <input type="hidden" name="field" value="<%= params[:field].present? ? params[:field] : 'name' %>"/>
          <input placeholder="输入关键字，按回车键提交" value="<%= params[:keyword] %>" name="keyword" type="text" class="form-control" aria-label="...">
        </div>
      </form>
    </div>
  </div>
</div>

<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th><%= t('simple_form.labels.defaults.name') %></th>
    <th>创建时间</th>
    <th>更新时间</th>
    <th>操作</th>
  </tr>
  </thead>

  <tbody>
  <% @news_types.each do |news_type| %>
      <tr>
        <td><%= news_type.id %></td>
        <td><%= news_type.name %></td>
        <td><%= news_type.created_at.try(:strftime, '%Y-%m-%d %H:%M:%S') %></td>
        <td><%= news_type.updated_at.try(:strftime, '%Y-%m-%d %H:%M:%S') %></td>

        <td><%= link_to [:admin, news_type], title: '查看', class: 'btn btn-xs btn-warn' do %>
              <i class="icon-eye-open bigger-120"></i>
          <% end %>
          <%= link_to edit_admin_news_type_path(news_type), title: '编辑', class: 'btn btn-xs btn-info' do %>
              <i class="icon-edit bigger-120"></i>
          <% end %>
          <%= link_to [:admin, news_type], method: :delete, data: {confirm: '确认删除吗?'}, title: '删除', class: 'btn btn-xs btn-danger' do %>
              <i class="icon-trash bigger-120"></i>
          <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<nav>
  <%= paginate @news_types %>
</nav>

app/views/admin/news_types/new.html.erb
<h1 class="page-header">
  新增<%= t('activerecord.models.news_type') %>
  <small class="pull-right">
    <a href="<%= admin_news_types_path %>" class="btn btn-default" title="新闻类型列表">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<%= render 'form' %>

app/views/admin/news_types/show.html.erb
<h1 class="page-header">
  显示<%= t('activerecord.models.news') %>
  <small class="pull-right">
    <a href="<%= edit_admin_news_type_path(@news_type) %>" title="编辑" class="btn btn-default">
      <i class="icon-edit icon-only"></i></a>
    <a href="<%= admin_news_types_path %>" title="列表" class="btn btn-default">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>
<div class="panel panel-info">
  <div class="panel-heading">
    <%= t('activerecord.models.news_type') %>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <h4><%= t('simple_form.labels.defaults.name') %>:</h4>

      <%= @news_type.name %>
    </li>
  </ul>
</div>