config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'competition' => 'competitions#index'
  get 'competitions/team/:id' => 'competitions#team'
  get 'competitions/shows' => 'competitions#shows'
  get 'competitions/login_in' => 'competitions#login_in'
  resources :competitions, only: [:index, :show] do
    collection do
      post :valid_create_team
      post :add_user_apply_info
      get :apply_in
      get :event_teams
      post :reduce_team_amount
      post :delete_team
      post :leader_delete_player
      post :valid_team_code
      post :send_email_code
      post :reset_team_code_by_mobile
      post :reset_team_code_by_email
    end
  end
  resources :creative_activities
  resources :news

  devise_for :users, path: 'account', controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  captcha_route

  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  mount API_v1::API => '/'

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/mobile' => 'user#mobile', as: 'user_mobile', via: [:get, :post]
  match 'user/add_mobile' => 'user#add_mobile', as: 'user_add_mobile', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get, :post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get, :post]
  match 'user/creative_activity' => 'user#creative_activity', as: 'user_creative_activity', via: [:get, :post]
  get 'user/activity_show' => 'user#activity_show'
  get 'user/comp_show' => 'user#comp_show'
  post 'user/update_team_cover' => 'user#update_team_cover', as: 'user_update_team_cover'
  get 'discourse/sso' => 'discourse_sso#sso'
  namespace :user do |u|

    resources :likes, only: [:index, :create, :destroy]

  end
  get 'test' => 'test#index'

  get '/admin/' => 'admin#index'

  namespace :admin do |admin|

    resources :accounts, only: [:new, :index, :create, :destroy] do
      collection do
        get :change_password
        post :change_password_post
      end
    end

    resources :admins
    resources :competitions do
      collection do
        get :get_events
      end
    end
    resources :events do
      collection do
        get :teams
        get :scores
        get :add_score
        post :add_score
        get :edit_score
        post :edit_score
        post :create_team
        post :add_team_player
        post :delete_team_player
        post :delete_team
      end
    end
    resources :users
    resources :organizers
    resources :teams
    resources :creative_activities do
      collection do
        post :add_expert_score
        post :edit_expert_score
        post :audit
      end
    end
    resources :scores do
      collection do
        post :get_teams
      end
    end
    resources :news
    resources :news_types
    resources :schedules
    resources :referees
    resources :roles
    resources :districts
    resources :vouchers

  end

  namespace :kindeditor do
    post '/upload' => 'assets#create'
    get '/filemanager' => 'assets#list'
  end

  if Rails.env.development?
  end

end

app/models/creative_activity.rb
class CreativeActivity < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :users, through: :like
  has_many :likes, foreign_key: :creative_activity_id

  validates :name, presence: true, length: {in: 1..20}
  validates :user_id, presence: true
  validates :cover, presence: true
  before_validation :validate

  def validate
    unless cover.present?
      errors[:cover] << '请上传一张海报(图片)'
    end
  end

  mount_uploader :cover, CoverUploader
  mount_uploader :file, FileUploader
  mount_uploader :media, MediaUploader


end

app/controllers/admin/creative_activities_controller.rb
class Admin::CreativeActivitiesController < AdminController
  before_action :set_creative_activity, only: [:show, :edit, :update, :destroy]
  before_action do
    authenticate_permissions(['super_admin','admin','editor','audit'])
  end


  def index
    if params[:field].present? && params[:keyword].present?
      @activities = CreativeActivity.all.where(["#{params[:field]} like ?", "%#{params[:keyword]}%"]).per_page_kaminari(params[:page]).per(params[:per])
    else
      @activities = CreativeActivity.all.per_page_kaminari(params[:page]).per(params[:per])
    end
  end


  def show
  end

  def new
    @activity = CreativeActivity.new
  end

  def edit
  end


  def create
    @activity = CreativeActivity.new(creative_activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to [:admin, @activity], notice: '作品创建成功.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @activity.update(creative_activity_params)
        format.html { redirect_to [:admin, @activity], notice: '作品更新成功.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to admin_creative_activities_url, notice: '作品删除成功.' }
      format.json { head :no_content }
    end
  end

  def add_expert_score
    activity = CreativeActivity.find(params[:activity_id])
    activity.expert_score = params[:expert_score]
    activity.last_score = (activity.expert_score.to_f + activity.likes_count).to_s
    if activity.save
      result = [true, '评分成功']
    else
      result = [false, '评分过程出现意外']
    end
    render json: result
  end

  def edit_expert_score
    activity = CreativeActivity.find(params[:activity_id])
    activity.expert_score = params[:expert_score]
    activity.last_score = (activity.expert_score.to_f + activity.likes_count).to_s
    if activity.save
      result = [true, '评分更改成功']
    else
      result = [false, '评分修改过程出现意外']
    end
    render json: result
  end


  def audit
    if request.method == 'POST'
      activity = CreativeActivity.find(params[:activity_id])
      activity.is_audit = params[:status].to_i
      if activity.save
        result = [true, '操作成功!']
      else
        result = [true, '操作失败!']
      end
      render json: result
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_creative_activity
    @activity = CreativeActivity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def creative_activity_params
    params.require(:creative_activity).permit!
  end
end

app/controllers/creative_activities_controller.rb
class CreativeActivitiesController < ApplicationController
  before_action :set_creative_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit]
  # GET /creative_activities
  # GET /creative_activities.json
  def index
    @creative_activities = CreativeActivity.all.per_page_kaminari(params[:page]).per(params[:per])
  end

  # GET /creative_activities/1
  # GET /creative_activities/1.json
  def show
    if current_user.present?
      @user_likes = current_user.likes.pluck(:creative_activity_id)
    end
  end

  # GET /creative_activities/new
  def new
    @creative_activity = CreativeActivity.new
  end

  # GET /creative_activities/1/edit
  def edit
  end

  # POST /creative_activities
  # POST /creative_activities.json
  def create
    @creative_activity = CreativeActivity.new(creative_activity_params)

    respond_to do |format|
      if @creative_activity.save


        format.html { redirect_to @creative_activity, notice: '创意活动创建成功' }
        format.json { render :show, status: :created, location: @creative_activity }
      else
        format.html { render :new }
        format.json { render json: @creative_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creative_activities/1
  # PATCH/PUT /creative_activities/1.json
  def update
    respond_to do |format|
      if @creative_activity.update(creative_activity_params)
        format.html { redirect_to @creative_activity, notice: '创意活动更新成功' }
        format.json { render :show, status: :ok, location: @creative_activity }
      else
        format.html { render :edit }
        format.json { render json: @creative_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creative_activities/1
  # DELETE /creative_activities/1.json
  def destroy
    @creative_activity.destroy
    respond_to do |format|
      format.html { redirect_to creative_activities_url, notice: '创意活动删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_creative_activity
    @creative_activity = CreativeActivity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def creative_activity_params
    params.require(:creative_activity).permit(:name, :cover, :file, :media, :description, :user_id)
  end
end

app/views/admin/creative_activities/_form.html.erb
<style type="text/css">
    textarea, input[type="text"] {
        padding: 0 4px;
    }
</style>
<div class="panel panel-info">
  <div class="panel-heading"><%= t('activerecord.models.creative_activity') %></div>
  <div class="panel-body">
    <%= simple_form_for([:admin, @activity]) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.hidden_field :user_id, value: 0 %>
          <%= f.input :name %>
          <%= f.input :event_id, collection: Event.where(status: 0) %>
          <div class="form-group">
            <label for="exampleInputFile"><abbr title="必填字段">*</abbr> 海报</label>
            <%= f.file_field :cover, :label => '海报' %>
            <%= f.hidden_field :cover_cache %>
            <p class="help-block">格式：jpg jpeg gif png，尺寸：800x800</p>
          </div>
          <label class="select required control-label" for="creative_activity_description"><abbr title="必填字段">*</abbr>内容:</label>
          <%= f.kindeditor :description, :window_onload => true, :owner_id => @activity.id, :items => ['source', 'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline', 'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist', 'insertunorderedlist', '|', 'emoticons', 'image', 'media', 'insertfile', 'baidumap', 'link', 'unlink', 'quickformat', 'preview', 'fullscreen'] %>

          <!--<%= f.input :likes_count %>-->
          <!--<%= f.input :expert_score %>-->
          <!--<%= f.input :last_score %>-->
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>
<script type="text/javascript" src="/assets/kindeditor.js"></script>

app/views/admin/creative_activities/edit.html.erb
<h1 class="page-header">
  编辑<%= t('activerecord.models.creative_activity') %>
  <small class="pull-right">
    <a href="<%= admin_creative_activity_path(@activity) %>" title="显示该作品" class="btn btn-default">
      <i class="icon-eye-open icon-only"></i></a>
    <a href="<%= admin_creative_activities_path %>" title="作品列表" class="btn btn-default">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<style type="text/css">
    textarea, input[type="text"] {
        padding: 0 4px;
    }
</style>
<div class="panel panel-info">
  <div class="panel-heading"><%= t('activerecord.models.creative_activity') %></div>
  <div class="panel-body">
    <%= simple_form_for([:admin, @activity]) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <div class="form-group string optional creative_activity_user_id">
            <label class="string optional control-label" for="creative_activity_user_id">作者</label>
            <input id="creative_activity_user_id" class="string optional form-control" type="text" disabled value="<%= @activity.user_id==0 ? '官方发布' : @activity.user.nickname %>" name="creative_activity[user_id]">
          </div>
          <%= f.input :name %>
          <label class="select required control-label" for="creative_activity_description"><abbr title="必填字段">*</abbr>内容:</label>
          <%= f.kindeditor :description, :window_onload => true, :owner_id => @activity.id, :items => ['source', 'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline', 'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist', 'insertunorderedlist', '|', 'emoticons', 'image', 'media', 'insertfile', 'baidumap', 'link', 'unlink', 'quickformat', 'preview', 'fullscreen'] %>
          <% if @activity.cover? %>
              <div class="form-group">
                <%= image_tag(@activity.cover_url(:middle), class: 'img-thumbnail') %>
              </div>
          <% end %>
          <%= f.input :cover, :label => '海报' %>
          <div class="form-group integer optional creative_activity_likes_count">
            <label class="integer optional control-label" for="creative_activity_likes_count">点赞数</label>
            <input id="creative_activity_likes_count" class="numeric integer optional form-control" type="number" disabled value="<%= @activity.likes_count %>" step="1" name="creative_activity[likes_count]">
          </div>
          <%= f.input :expert_score %>
          <!--<%= f.input :last_score %>-->
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>
<script type="text/javascript" src="/assets/kindeditor.js"></script>

app/views/admin/creative_activities/index.html.erb
<h1 class="page-header">
  <%= t('activerecord.models.creative_activity') %>列表
  <small class="pull-right">
    <a href="<%= new_admin_creative_activity_path %>" class="btn btn-default" title="添加作品">
      <i class="icon-only icon-plus"></i></a>
    <a href="#" class="btn btn-default btn-search-toggle" title="搜索">
      <i class="icon-search icon-only"></i>
    </a>
  </small>
</h1>
<div class="widget-box form-search-toggle <%= params[:field].present? && params[:keyword].present? ? 'show' : 'hide' %>">
  <div class="widget-header widget-header-small">
    <h5 class="lighter">搜索</h5>
  </div>
  <div class="widget-body">
    <div class="widget-main">
      <form class="form" role="form" method="get">
        <div class="input-group" data-search="field">
          <div class="input-group-btn">
            <button type="button" class="btn btn-white dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
              <span data-search-text class="admin-search-field"><%= t('simple_form.labels.defaults.name') %></span>
              <span class="caret"></span></button>
            <ul class="dropdown-width dropdown-menu">
              <li data-search-option="name"><a><%= t('simple_form.labels.defaults.name') %></a></li>
              <li data-search-option="id"><a>ID</a></li>
            </ul>
          </div>
          <input type="hidden" name="field" value="<%= params[:field].present? ? params[:field] : 'name' %>"/>
          <input placeholder="输入关键字，按回车键提交" value="<%= params[:keyword] %>" name="keyword" type="text" class="form-control" aria-label="...">
        </div>
      </form>
    </div>
  </div>
</div>

<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>作者</th>
    <th><%= t('simple_form.labels.defaults.name') %></th>
    <th>描述</th>
    <th>审核状态</th>
    <th>点赞数</th>
    <th>专家评分</th>
    <th>总分</th>
    <th>操作</th>
  </tr>
  </thead>

  <tbody>
  <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.id %></td>
        <td><%= activity.user_id==0 ? '官方发布' : "#{activity.user.nickname}" %></td>
        <td><%= activity.name %></td>
        <td><%= "#{(activity.description).at(0..20)}......" if activity.description.length > 20 %></td>
        <td>
          <% if activity.is_audit == 1 %>
              <span class="btn btn-xs btn-primary switch-audit-user-activity" data-id="<%= activity.id %>">通过</span>
          <% elsif activity.is_audit == 2 %>
              <span class="btn btn-xs btn-danger btn-primary switch-audit-user-activity" data-id="<%= activity.id %>">未通过</span>
          <% else %>
              <span class="btn btn-xs btn-info audit-user-activity" id="<%= "audit-result#{activity.id}" %>" data-id="<%= activity.id %>">待审核</span>
          <% end %>
        </td>
        <td id="<%= "like-count#{activity.id}" %>"><%= activity.likes_count %></td>
        <td>
          <% if activity.expert_score.present? %>
              <span class="btn btn-xs btn-info edit-expert-score" id="<%= "edit-expert-score#{activity.id}" %>" title="编辑分数" data-id="<%= activity.id %>"><%= activity.expert_score %></span>
          <% else %>
              <button class="btn btn-xs btn-warning add-expert-score" id="<%= "add-expert-score#{activity.id}" %>" type="button" data-id="<%= activity.id %>">评分</button>
          <% end %>
        </td>

        <td id="<%= "last-score#{activity.id}" %>">
          <% if activity.last_score.present? %>
              <%= activity.last_score %>
          <% end %>
        </td>

        <td><%= link_to [:admin, activity], title: '查看', class: 'btn btn-xs btn-warn' do %>
              <i class="icon-eye-open bigger-120"></i>
          <% end %>
          <%= link_to edit_admin_creative_activity_path(activity), title: '编辑', class: 'btn btn-xs btn-info' do %>
              <i class="icon-edit bigger-120"></i>
          <% end %>
          <%= link_to [:admin, activity], method: :delete, data: {confirm: '确认删除吗?'}, title: '删除', class: 'btn btn-xs btn-danger' do %>
              <i class="icon-trash bigger-120"></i>
          <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<nav>
  <%= paginate @activities %>
</nav>

app/views/admin/creative_activities/new.html.erb
<h1 class="page-header">
  新增<%= t('activerecord.models.creative_activity') %>
  <small class="pull-right">
    <a href="<%= admin_creative_activities_path %>" class="btn btn-default" title="作品列表">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<%= render 'form' %>

app/views/admin/creative_activities/show.html.erb
<h1 class="page-header">
  显示<%= t('activerecord.models.creative_activity') %>
  <small class="pull-right">
    <a href="<%= edit_admin_creative_activity_path(@activity) %>" title="编辑" class="btn btn-default">
      <i class="icon-edit icon-only"></i></a>
    <a href="<%= admin_creative_activities_path %>" title="列表" class="btn btn-default">
      <i class="icon-list icon-only"></i></a>
  </small>
</h1>

<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>
<div class="panel panel-info">
  <div class="panel-heading">
    <%= t('activerecord.models.creative_activity') %>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <h4><%= t('simple_form.labels.defaults.name') %>:</h4>

      <%= @activity.name %>
    </li>

    <li class="list-group-item">
      <h4>作者:</h4>

      <%= @activity.user_id == 0 ? '官方发布' : "#{@activity.user.nickname}" %>
    </li>
    <% if @activity.cover? %>
        <li class="list-group-item">
          <h4>海报:</h4>

          <%= image_tag(@activity.cover_url(:middle)) %>
        </li>
    <% end %>
    <% if @activity.description? %>
        <li class="list-group-item">
          <h4>描述:</h4>

          <%= @activity.description.html_safe %>
        </li>
    <% end %>
    <li class="list-group-item">
      <h4>点赞数:</h4>

      <%= @activity.likes_count %>
    </li>
    <li class="list-group-item">
      <h4>专家评分:</h4>

      <%= @activity.expert_score %>
    </li>
    <li class="list-group-item">
      <h4>总分:</h4>

      <%= @activity.last_score %>
    </li>


  </ul>
</div>