config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'competition' => 'competitions#index'
  get 'competitions/team/:id' => 'competitions#team'
  get 'competitions/shows' => 'competitions#shows'
  get 'competitions/login_in' => 'competitions#login_in'
  resources :competitions, only: [:index, :show] do
    collection do
      post :valid_create_team
      post :add_user_apply_info
      get :apply_in
      get :event_teams
      post :reduce_team_amount
      post :delete_team
      post :leader_delete_player
      post :valid_team_code
      post :send_email_code
      post :reset_team_code_by_mobile
      post :reset_team_code_by_email
    end
  end
  resources :creative_activities
  resources :news

  devise_for :users, path: 'account', controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  captcha_route

  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  mount API_v1::API => '/'

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/mobile' => 'user#mobile', as: 'user_mobile', via: [:get, :post]
  match 'user/add_mobile' => 'user#add_mobile', as: 'user_add_mobile', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get, :post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get, :post]
  match 'user/creative_activity' => 'user#creative_activity', as: 'user_creative_activity', via: [:get, :post]
  get 'user/activity_show' => 'user#activity_show'
  get 'user/comp_show' => 'user#comp_show'
  post 'user/update_team_cover' => 'user#update_team_cover', as: 'user_update_team_cover'
  get 'discourse/sso' => 'discourse_sso#sso'
  namespace :user do |u|

    resources :likes, only: [:index, :create, :destroy]

  end
  get 'test' => 'test#index'

  get '/admin/' => 'admin#index'

  namespace :admin do |admin|

    resources :accounts, only: [:new, :index, :create, :destroy] do
      collection do
        get :change_password
        post :change_password_post
      end
    end

    resources :admins
    resources :competitions do
      collection do
        get :get_events
      end
    end
    resources :events do
      collection do
        get :teams
        get :scores
        get :add_score
        post :add_score
        get :edit_score
        post :edit_score
        post :create_team
        post :add_team_player
        post :delete_team_player
        post :delete_team
      end
    end
    resources :users
    resources :organizers
    resources :teams
    resources :creative_activities do
      collection do
        post :add_expert_score
        post :edit_expert_score
        post :audit
      end
    end
    resources :scores do
      collection do
        post :get_teams
      end
    end
    resources :news
    resources :news_types
    resources :schedules
    resources :referees
    resources :roles
    resources :districts
    resources :vouchers

  end

  namespace :kindeditor do
    post '/upload' => 'assets#create'
    get '/filemanager' => 'assets#list'
  end

  if Rails.env.development?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    if params[:field].present? && params[:keyword].present?
      @users = User.all.where(["#{params[:field]} like ?", "%#{params[:keyword]}%"]).per_page_kaminari(params[:page]).per(params[:per])
    else
      @users = User.includes(:user_profile).all.per_page_kaminari(params[:page]).per(params[:per])
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: t('activerecord.models.user') + ' 已成功创建.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: t('activerecord.models.user') + ' 已成功更新.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: t('activerecord.models.user') + ' 已成功删除.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :nickname, :mobile, :email)
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :authenticate

  # def index
  #   @favorites = current_user.likes.includes(:creative_activity).all
  #   @user_favorites = @favorites.pluck(:creative_activity_id)
  # end


  def create
    @creative_activity = CreativeActivity.find(params[:id])
    @status, @is_present = Like.toggle(current_user.id, @creative_activity.id)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  before_action do
    @channel = '/channel'
    if params[:user_id].present?
      @channel += '/' + params[:user_id]
    end
  end

  before_action do
    $chats ||= {}
    $chats[@channel] ||= []
  end


  # 个人信息概览
  def preview

  end

  # 修改个人信息
  def profile
    # 获取Profile
    @user_profile = current_user.user_profile ||= current_user.build_user_profile
    if request.method == 'POST'
      # 过滤Profile参数
      profile_params = params.require(:user_profile).permit(:username, :autograph, :age, :school, :grade, :gender, :bj, :birthday, :address)
      @user_profile.username = profile_params[:username]
      @user_profile.autograph = profile_params[:autograph]
      @user_profile.school = profile_params[:school]
      @user_profile.grade = profile_params[:grade]
      @user_profile.bj = profile_params[:bj]
      @user_profile.age = profile_params[:age]
      @user_profile.gender = profile_params[:gender]
      @user_profile.birthday = profile_params[:birthday]
      @user_profile.address = profile_params[:address]
      if @user_profile.save
        flash[:success] = '详细信息更新成功'
      else
        flash[:error] = '详细信息更新失败'
      end
      redirect_to user_profile_path
    end
  end

  # 更新头像和 nickname
  def update_avatar
    if current_user.update_attributes(params.require(:user).permit(:nickname, :avatar))
      flash[:success] = '个人信息更新成功'
    elsif User.where(nickname: params[:user][:nickname]).where.not(id: current_user.id).take.present?
      flash[:error] = params[:user][:nickname]+'已被使用,请使用其他昵称!'
    else
      flash[:error] = '个人信息更新失败'
    end
    redirect_to user_profile_path
  end

  # 头像删除
  def remove_avatar
    if current_user.avatar?
      current_user.remove_avatar!
      current_user.avatar = nil
      current_user.save
      flash[:success] = '头像已成功删除'
    end
    redirect_to user_profile_path
  end

  def comp
    @user_events = TeamUserShip.includes(:event).where(user_id: current_user.id).select(:id, :event_id, :team_id).per_page_kaminari(params[:page]).per(params[:per])
  end

  def comp_show
    @no_access = TeamUserShip.where(user_id: current_user.id, team_id: params[:id]).exists?
    if @no_access
      @team = Team.find(params[:id])
      @players = TeamUserShip.includes(:user).where(team_id: params[:id])
      @team_scores = Score.includes(:schedule, :team1, :team2).where(['team1_id = :value OR team2_id = :value', {:value => 3}]).select(:team1_id, :team2_id, :score1, :score2, :th, :comp_name, :kind).map { |s| {
          team1: s.team1.identifier,
          team2: s.team2.identifier,
          identifier1: s.team1.identifier,
          identifier2: s.team2.identifier,
          cover1: ActionController::Base.helpers.asset_path(s.team1.cover_url(:small)),
          cover2: ActionController::Base.helpers.asset_path(s.team2.cover_url(:small)),
          score1: s.score1,
          score2: s.score2,
          th: s.th.to_s,
          comp_name: s.schedule.name,
          kind: t('kind.kind'+s.kind.to_s)
      } }
    end
  end

  def update_team_cover
    @team = Team.find(params[:team][:id])
    if current_user.id == @team.user_id
      @team.update_attributes(params.require(:team).permit(:cover))
      if @team.save
        flash[:success] = '队伍头像上传成功'
      else
        flash[:error] = '队伍头像上传失败'
      end
    else
      flash[:error] = '非法请求'
    end
    redirect_to '/user/comp_show?id='+params[:team][:id].to_s
  end

  def creative_activity
    @creative_activities = CreativeActivity.where(user_id: current_user.id).per_page_kaminari(params[:page]).per(params[:per])
  end

  def activity_show
    @creative_activity = CreativeActivity.find(params[:id])
  end


  # 修改密码请求
  def passwd
    if request.method == 'POST'

      status, message = self.change_password(current_user.nickname, params[:user][:old_password], params[:user][:new_password], params[:user][:confirm_password])
      if status
        sign_out @user
        redirect_to new_user_session_path

        flash[:success] = message
      else
        flash[:error] = message
      end
    end
  end

  #修改密码方法
  def change_password(nickname, old_password, new_password, confirm_password)
    user = User.find_by_nickname(nickname)
    unless user.present?
      return [FALSE, '用户不存在']
    end

    unless old_password.present?
      return [FALSE, '原密码不能为空']
    end

    unless new_password.present?
      return [FALSE, '新密码不能为空']
    end

    unless new_password.length <= 20 && new_password.length >= 6
      return [FALSE, '新密码只能为6-20位']
    end

    unless confirm_password == new_password
      return [FALSE, '新密码两次输入不一致']
    end

    unless user.valid_password?(old_password)
      return [FALSE, '原密码不正确']
    end


    if user.valid_password?(old_password)
      user.password = new_password
      if user.save
        [TRUE, '密码已成功修改，请重新登录。']
      else
        [FALSE, '密码修改过程出错']
      end
    else
      [FALSE, '原密码不正确']
    end
  end

  # 修改手机号
  def mobile
    @reset_mobile = ResetMobile.new
    if request.method == 'POST'
      @reset_mobile.password = params[:reset_mobile][:password]
      @reset_mobile.new_mobile = params[:reset_mobile][:new_mobile]
      @reset_mobile.mobile_code = params[:reset_mobile][:mobile_code]
      status, message = self.change_mobile(current_user.mobile, params[:reset_mobile][:new_mobile], params[:reset_mobile][:password], params[:reset_mobile][:mobile_code])

      if status
        sign_out @user
        redirect_to new_user_session_path

        flash[:success] = message
      else
        flash[:error] = message
      end
    end

  end

  def add_mobile
    if request.method == 'POST'
      current_user.mobile = params[:user][:mobile]
      current_user.mobile_code = params[:user][:mobile_code]
      if params[:user][:mobile].present?
        status, message = self.add_mobile_validate(current_user, params[:user][:mobile], params[:user][:mobile_code])
        if status
          flash[:success]= message
        else
          flash[:error] = message
        end
      else
        flash[:error] = '手机号不能为空'
      end

    end

  end

  def add_mobile_validate(current_user, mobile, mobile_code)
    unless current_user.present?
      return [FALSE, '原用户不存在，请重新登录']
    end
    user = User.find_by_mobile(mobile)
    unless user.blank?
      return [FALSE, '该手机号已经被使用']
    end
    status, message = SMSService.new(mobile).validate?(mobile_code, SMSService::TYPE_CODE_ADD_MOBILE)
    unless status
      return [FALSE, message]
    end
    if status
      current_user.mobile = mobile
      if current_user.save
        [TRUE, '手机号已成功添加']
      end

    else
      [FALSE, '添加手机号过程出错']
    end

  end

  # 修改手机号方法
  def change_mobile(old_username, new_username, password, mobile_code)
    user = User.find_by_mobile(old_username)
    unless user.present?
      return [FALSE, '原用户不存在，请重新登录']
    end
    unless password.present?
      return [FALSE, '密码不能为空']
    end

    unless user.valid_password?(password)
      return [FALSE, '密码不正确']
    end

    unless new_username.present?
      return [FALSE, '新手机号不能为空']
    end

    unless Regular.is_mobile?(new_username)
      return [FALSE, '新手机号格式错误']
    end

    unless mobile_code.present?
      return [FALSE, '验证码不能为空']
    end
    status, message = SMSService.new(new_username).validate?(mobile_code, SMSService::TYPE_CODE_RESET_MOBILE)

    unless status
      return [FALSE, message]
    end
    if user.valid_password?(password)
      user.mobile = new_username
      if user.save
        [TRUE, '手机号已成功修改，请重新登录。']
      else
        [FALSE, '手机号修改过程出错']
      end
    end
  end

  def notification
    @notifications = Notification.where(user_id: current_user.id)
  end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/_menu.erb
<div class="menu-item clearfix">
  <%= simple_form_for(current_user, html: {id: 'form_change_avatar', multipart: true}, url: user_update_avatar_path, method: :post) do |f| %>
      <div class="avatar">
        <%= image_tag(current_user.avatar_url(:middle), class: 'avatar-img') %>
      </div>
      <label class="edit-avatar" for="user_avatar">修改头像</label>

      <div class="username">
        <div class="edit" data-edit="text" data-name="user[nickname]" title="点击编辑">
          <%= current_user.nickname %>
        </div>
        <input type="hidden" name="user[nickname]" value="<%= current_user.nickname %>"/>
      </div>
      <div class="clearfix"></div>
      <div class="edit-plus">
        <%= f.file_field :avatar %>
        <%= f.submit class: 'btn-user-update', value: '更新个人信息' %>
      </div>
  <% end %>
</div>
<div class="<%= "menu-item #{'active' if action_name=='profile'}" %>">
  <a class="t-18" href="<%= user_profile_path %>">我的资料</a>
</div>
<div class="<%= "menu-item #{'active' if action_name=='comp' || action_name=='comp_show'}" %>">
  <a href="<%= user_comp_path %>" class="t-18">我的比赛</a>
</div>
<div class="<%= "menu-item #{'active' if action_name=='creative_activity' || action_name=='activity_show'}" %>">
  <a href="<%= user_creative_activity_path %>" class="t-18">我的作品</a>
</div>

app/views/user/_tab.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li <%= 'class=active' if action_name == 'preview' %>>
    <a href="<%= user_preview_path %>"><span class="hidden-xs">信息</span>概览</a>
  </li>
  <li <%= 'class=active' if action_name == 'profile' %>>
    <a href="<%= user_profile_path %>"><span class="hidden-xs">个人</span>信息</a>
  </li>
  <li <%= 'class=active' if action_name == 'passwd' %>>
    <a href="<%= user_passwd_path %>"><span class="hidden-xs">修改</span>密码</a>
  </li>
  <% if current_user.mobile.present? %>
      <li <%= 'class=active' if action_name == 'mobile' %>>
        <a href="<%= user_mobile_path %>"><span class="hidden-xs">修改</span>手机号</a>
      </li>
  <% else %>
      <li <%= 'class=active' if action_name == 'add_mobile' %>>
        <a href="<%= user_add_mobile_path %>"><span class="hidden-xs">添加</span>手机号</a>
      </li>
  <% end %>
</ul>
<br>

app/views/user/activity_show.html.erb
<div class="floor">
  <div id="nav" class="nav-v2">
    <%= render 'layouts/nav_menu' %>
  </div>
  <div class="container-content">
    <div id="user-info">
      <div class="menu">
        <%= render 'user/menu' %>
      </div>
      <div class="content">
        <div class="activity-panel">
          <div class="activity-title">
            <div class="col-l">
              <p class="t-20 t-bold pull-down-5"><%= @creative_activity.name %></p>

              <p class="t-12 grey">上传时间：<%= @creative_activity.created_at.try(:strftime, '%Y-%m-%d') %></p>

              <div class="pull-down-10">
                <% if @creative_activity.is_audit==0 %>
                    <label class="t-14 label label-default">待审核</label>
                <% elsif @creative_activity.is_audit == 1 %>
                    <label class="t-14 label label-success">审核通过</label>
                <% else %>
                    <label class="t-14 label label-danger">审核未通过</label>
                <% end %>
              </div>
            </div>
            <div class="col-r">
              <div class="btn-rate">
                <a href="<%= user_creative_activity_path %>" class="btn-back-to-list">返回列表</a>
              </div>
            </div>
          </div>
          <div class="activity-content">
            <% if @creative_activity.cover? %>
                <div class="form-group pull-down-20">
                  <%= image_tag(@creative_activity.cover_url(:middle), class: 'img-thumbnail') %>
                </div>
            <% end %>
            <% if @creative_activity.file? %>
                <div class="form-group pull-down-20">
                  <%= @creative_activity.file %>
                  <%= link_to '下载附件', @creative_activity.file_url %>
                </div>
            <% end %>
            <div class="form-group pull-down-20">
              <% if @creative_activity.media? %>
                  <embed src="/assets/kindeditor/plugins/ckplayer/ckplayer.swf" flashvars="p=0&f=<%= @creative_activity.media_url %>"
                         type="application/x-shockwave-flash" width="550" height="400" autostart="false" loop="true">
                  </embed>
                  <%= link_to '下载音频', @creative_activity.media_url %>
              <% end %>
            </div>
            <!--富文本内容-->
            <%= @creative_activity.description.html_safe %>
            <!--富文本内容结束-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/add_mobile.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3 hidden-xs">
      <%= render 'user/menu' %>
    </div>
    <div class="col-xs-12 col-sm-9">
      <h1 class="page-header">
        我的账户
      </h1>

      <%= render 'user/tab' %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= simple_form_for(current_user, html: {id: 'form_add_mobile'}, url: user_add_mobile_path, method: :post) do |f| %>
              <div class="form-inputs">
                <%= f.input :mobile, placeholder: '请输入新的手机号' %>
                <div class="row">
                  <%= f.input :mobile_code, as: :tel, placeholder: '输入验证码', wrapper_html: {class: 'col-md-3'} %>
                  <div class="form-group tel required sing_up_mobile_code col-md-3">
                    <label class="control-label hidden-xs">
                      &nbsp;
                    </label>
                    <button type="button" data-key="add_mobile_new" data-type="ADD_MOBILE" id="btn_send_mobile_code" class="btn btn-default btn-block">获取验证码</button>
                  </div>
                </div>

              </div>
              <div class="form-actions">
                <%= f.submit class: 'btn btn-primary', value: '添加手机号' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/profile.html.erb
<!--<div class="container">-->
<!--<div class="row">-->
<!--<div class="col-xs-12 col-sm-3 hidden-xs">-->
<!--<%= render 'user/menu' %>-->
<!--</div>-->
<!--<div class="col-xs-12 col-sm-9">-->
<!--<h1 class="page-header">-->
<!--我的账户-->
<!--</h1>-->

<!--<%= render 'user/tab' %>-->
<!--<div class="panel panel-default">-->
<!--<div class="panel-body">-->
<!--<%= simple_form_for(current_user, html: {id: 'form_change_avatar', multipart: true}, url: user_update_avatar_path, method: :post) do |f| %>-->
    <!--<div class="form-inputs">-->
    <!--<div class="row">-->
    <!--<div class="col-sm-4">-->
    <!--<div class="form-group">-->
    <!--<p>-->
    <!--<%= image_tag(current_user.avatar_url(:middle), class: 'img-thumbnail') %>-->
    <!--</p>-->
    <!--
    <% if current_user.avatar? %>-->
        <!--<%= link_to '删除头像', user_remove_avatar_path, data: {method: :post, confirm: '确认删除头像吗？'}, class: 'btn btn-danger' %>-->
        <!--
    <% end %>-->
    <!--</div>-->
    <!--</div>-->
    <!--<div class="col-sm-8">-->
    <!--<div class="form-group">-->
    <!--<label for="user_avatar">选择头像</label>-->
    <!--<%= f.file_field :avatar %>-->
    <!--<p class="help-block">格式：jpg jpeg gif png，尺寸：400x400</p>-->
    <!--</div>-->
    <!--<%= f.hidden_field :avatar_cache %>-->
    <!--<%= f.input :nickname %>-->
    <!--<div class="form-actions">-->
    <!--<%= f.submit class: 'btn btn-primary', value: '更新个人信息' %>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--
<% end %>-->
<!--<hr>-->
<!--<h3 class="sub-header">详细信息</h3>-->
<!--<%= simple_form_for(@user_profile, html: {id: 'form_change_profile', multipart: true}, url: user_profile_path, method: :post) do |f| %>-->
    <!--<div class="row">-->
    <!--<div class="col-sm-12">-->
    <!--<div class="form-inputs">-->
    <!--<%= f.input :username %>-->
    <!--<%= f.input :gender, collection: UserProfile::GENDER.map { |key, val| [t('gender.'+key.to_s), val] } %>-->
    <!--<%= f.input :age %>-->
    <!--<%= f.input :school %>-->
    <!--<%= f.input :grade %>-->
    <!--<%= f.input :birthday, as: :date, html5: true %>-->
    <!--<%= f.input :address %>-->
    <!--</div>-->
    <!--<div class="form-actions">-->
    <!--<%= f.submit class: 'btn btn-primary', value: '更新详细信息' %>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--
<% end %>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->

<div class="floor" id="user">
  <div id="nav" class="nav-v2 container-layer">
    <%= render 'layouts/nav_menu' %>
  </div>
  <div class="container-content">
    <div id="user-info">
      <div class="menu">
        <%= render 'user/menu' %>
      </div>
      <div class="content">
        <%= simple_form_for(@user_profile, html: {id: 'form_change_profile', multipart: true}, url: user_profile_path, method: :post) do |f| %>
            <div class="signature">
              <div class="input-row">
                <label class="t-16 signature-label" for="user[signature]">签名：</label>
                    <textarea class="t-14 signature-input" name="user_profile[autograph]"
                              id="user_profile[autograph]"><%= @user_profile.autograph %></textarea>
              </div>
            </div>
            <div class="secret-info">
              <!--<p class="text-right">*以下默认为不公开信息，只做资料备份</p>-->

              <div class="input-row">
                <label class="user-label t-16">姓名：</label>
                <%= f.input :username %>
              </div>
              <div class="input-row">
                <label class="user-label t-16">性别：</label>
                <!--<%= f.input :gender, collection: UserProfile::GENDER.map { |key, val| [t('gender.'+key.to_s), val] } %>-->

                <label class="gender-radio"><input name="user_profile[gender]" value="1" type="radio" <%= 'checked="checked"' if @user_profile.gender==1 %> />男</label>
                <label class="gender-radio"><input name="user_profile[gender]" value="2" type="radio" <%= 'checked="checked"' if @user_profile.gender==2 %> />女</label>

              </div>
              <div class="input-row">
                <label class="user-label t-16">年龄：</label>
                <%= f.input :age %>
              </div>
              <div class="input-row">
                <label class="user-label t-16">学校：</label>
                <%= f.input :school %>
              </div>
              <div class="input-row" style="overflow: hidden">
                <div style="width: 230px;float: left;margin-right: 20px">
                  <label class="user-label t-16">年级：</label>
                  <%= f.input :grade, collection: {一年级: 1, 二年级: 2, 三年级: 3, 四年级: 4, 五年级: 5, 六年级: 6, 七年级: 7, 八年级: 8, 九年级: 9, }.map { |key, val| [key, val] } %>
                </div>
                <div style="width: 230px;float: left;">
                  <label class="user-label t-16">班级：</label>
                  <%= f.input :bj %>
                </div>
              </div>
            </div>
            <%= f.submit class: 'btn-save-user-info', value: '保存修改' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>